versions:
  #v6.6.4: "https://downloads-packages.s3.amazonaws.com/gitlab_6.6.4-omnibus-1.ubuntu.12.04_amd64.deb"
  #v6.7.2: "https://downloads-packages.s3.amazonaws.com/gitlab_6.7.2-omnibus-1.ubuntu.12.04_amd64.deb"
  #v6.7.5: "https://downloads-packages.s3.amazonaws.com/gitlab_6.7.5-omnibus-1.ubuntu.12.04_amd64.deb"
  #v6.8.1: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_6.8.1-omnibus.4-1_amd64.deb"
  #v6.8.2: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_6.8.2-omnibus-1_amd64.deb"
  #v6.9.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_6.9.0-omnibus-1_amd64.deb"
  #v6.9.2: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_6.9.2-omnibus.2-1_amd64.deb"
  #v7.0.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.0.0-omnibus-1_amd64.deb"
  #v7.1.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.1.0-omnibus-1_amd64.deb"
  #v7.2.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.2.0-omnibus.3-1_amd64.deb"
  #v7.3.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.3.0-omnibus-1_amd64.deb"
  #v7.4.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.4.0-omnibus-1_amd64.deb"
  #v7.5.3: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.5.3-omnibus.5.2.1.ci-1_amd64.deb"
  #v7.6.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.6.0-omnibus.5.3.0.ci-1_amd64.deb"
  #v7.7.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.7.0-omnibus.5.4.0.ci-1_amd64.deb"
  #v7.8.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.8.0-omnibus-1_amd64.deb"
  #v7.9.0: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.9.0-omnibus.2-1_amd64.deb"
  #v7.9.4: "https://downloads-packages.s3.amazonaws.com/ubuntu-12.04/gitlab_7.9.4-omnibus.1-1_amd64.deb"
  #v7.10.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.10.0~omnibus.4-1_amd64.deb/download"
  #v7.11.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.11.0~omnibus.1-1_amd64.deb/download"
  #v7.12.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.12.0~omnibus.1-1_amd64.deb/download"
  #v7.13.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.13.0-ce.0_amd64.deb/download"
  #v7.13.1: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.13.1-ce.0_amd64.deb/download"
  #v7.13.2: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.13.2-ce.0_amd64.deb/download"
  #v7.13.3: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.13.3-ce.1_amd64.deb/download"
  #v7.13.4: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.13.4-ce.0_amd64.deb/download"
  #v7.13.5: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.13.5-ce.0_amd64.deb/download"
  #v7.14.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_7.14.0-ce.0_amd64.deb/download"
  #v8.0.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.0.0-ce.0_amd64.deb/download"
  #v8.1.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.1.0-ce.0_amd64.deb/download"
  #v8.2.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.2.0-ce.0_amd64.deb/download"
  v8.3.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.3.0-ce.0_amd64.deb/download"
  v8.3.8: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.3.8-ce.0_amd64.deb/download"
  v8.3.9: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.3.9-ce.0_amd64.deb/download"
  v8.4.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.4.0-ce.0_amd64.deb/download"
  v8.4.9: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.4.9-ce.0_amd64.deb/download"
  v8.4.10: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.4.10-ce.0_amd64.deb/download"
  v8.5.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.5.0-ce.0_amd64.deb/download"
  v8.5.11: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.5.11-ce.0_amd64.deb/download"
  v8.5.12: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.5.12-ce.0_amd64.deb/download"
  v8.6.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.6.0-ce.0_amd64.deb/download"
  v8.6.7: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.6.7-ce.0_amd64.deb/download"
  v8.6.8: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.6.8-ce.0_amd64.deb/download"
  v8.7.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.7.0-ce.0_amd64.deb/download"
  v8.7.3: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.7.3-ce.0_amd64.deb/download"
  v8.7.6: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.7.6-ce.0_amd64.deb/download"
  v8.8.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.0-ce.0_amd64.deb/download"
  v8.8.2: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.2-ce.0_amd64.deb/download"
  v8.8.4: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.4-ce.0_amd64.deb/download"
  v8.8.5: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.5-ce.0_amd64.deb/download"
  v8.8.7: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.7-ce.0_amd64.deb/download"
  v8.9.6: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.9.6-ce.0_amd64.deb/download"
  v8.10.5: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.10.5-ce.0_amd64.deb/download"
  v8.11.0: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.0-ce.0_amd64.deb/download"
  v8.11.2: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.2-ce.0_amd64.deb/download"
  v8.11.3: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.3-ce.0_amd64.deb/download"
  v8.11.4: "https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.4-ce.0_amd64.deb/download"
